
stutest:
	python parser.py -s stutest1.in -s stutest2.in -s stutest3.in -s stutest4.in -s stutest5.in -s stutest6.in -s stutest7.in -s stutest8.in -s stutest9.in -s stutest10.in -s stutest11.in -s stutest12.in > stutest.out

proftest:
	python parser.py -s proftest.in > proftest.out

clean:
	rm -rf gforth.in
	rm -rf *.out

all: stutest
